### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by fvakiliev** [Flexberry/flexberry.github.io#107]
Hi FlexBerry!

When I try to build and start the flexberry server, I get the following error:

```
C:\Users\user\Documents\Projects\flexberry.github.io>bundle exec jekyll serve
Configuration file: C:/Users/user/Documents/Projects/flexberry.github.io/_config.yml
            Source: C:/Users/user/Documents/Projects/flexberry.github.io
       Destination: C:/Users/user/Documents/Projects/flexberry.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Liquid error (line 71): invalid byte sequence in UTF-8 in /_layouts/default.html
jekyll 3.8.5 | Error:  Liquid error (line 71): invalid byte sequence in UTF-8
```
Environment:
```
>ridk version
---
ruby:
  path: C:/Ruby26-x64
  version: 2.6.6
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.6-1
  git_commit: eb60b1c
msys2:
  path: C:\Ruby26-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 9.3.0
sh: GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.18363.778]
```

Thanks!
